### ISSUE TITLE
explode() expects parameter 2 to be string, array given

### ISSUE THREAD

**Issue by HarryBosh** [SocialiteProviders/Meetup#5]
Hello!

I am getting the following error:

Whoops, looks like something went wrong.

1/1
ErrorException in Arr.php line 238:
explode() expects parameter 2 to be string, array given
in Arr.php line 238
at HandleExceptions->handleError('2', 'explode() expects parameter 2 to be string, array given', '/home/vagrant/api/vendor/laravel/framework/src/Illuminate/Support/Arr.php', '238', array('array' => 'photo.photo_link', 'key' => array('birthday' => array('etc...

As per your documentation i am following the laravel way of handling authorisation however, using the code is failing, is this a user error or is something broken?

my code:

<?php

namespace App\Http\Controllers\Auth;

use Socialite;
use Illuminate\Routing\Controller;

class AuthMeetupController extends Controller
{
    /**
     * Redirect the user to the meetup authentication page.
     *
     * @return Response
     */
    public function redirectToProvider()
    {

        if(\Input::has('code')){
        	dd($this->handleProviderCallback());
        }
        return Socialite::driver('meetup')->redirect();

    }

    /**
     * Obtain the user information from meetup.
     *
     * @return Response
     */
    public function handleProviderCallback()
    {
     
        $user = Socialite::driver('meetup')->user();

        dump($user);

        // $user->token;
    }
}

http://stackoverflow.com/questions/33772273/laravel5-socialite-meetup-how-to-return-user

**Comment by HarryBosh** [comment]
in /home/vagrant/api/vendor/laravel/framework/src/Illuminate/Support/Arr.php line 238
at HandleExceptions->handleError('2', 'explode() expects parameter 2 to be string, array given', '/home/vagrant/api/vendor/laravel/framework/src/Illuminate/Support/Arr.php', '238', array('array' => 'photo.photo_link',

**Comment by AndyWendt** [comment]
@HarryBosh I will take a look at this.  The holidays have been crazy.  Sorry for the delay

**Comment by bspringston** [comment]
I too am having the same error

**Comment by AndyWendt** [comment]
@bspringston can you give me a full debug log?

**Comment by bspringston** [comment]
Thanks,

Robert M. Springston
CEO and Co-Founder
Quipley, Inc.
333 City Boulevard West
17th Floor
Orange, CA  92868

Phone: 714.937.2010
Mobile: 310.359.3816 | Email: bspringston@quipley.com <mailto:bspringston@gmail.com>
http://www.quipley.com <http://www.quipley/>

This item/document/material contains CONFIDENTIAL TRADE SECRET INFORMATION owned by Quipley, Inc. and/or its affiliated companies. This information is protected by applicable state law and may be protected by the federal Economic Espionage Act OF 1996 (18 U.S.C. Sec. 1831), which provides for criminal penalties of up to 15 years in prison and/or a $5 million fine for stealing, receiving, possessing and/or duplicating any information contained herein.

**Comment by AndyWendt** [comment]
@bspringston I didn't get a debug log.  @HarryBosh Are you running Laravel 5.2?

**Comment by bspringston** [comment]
I am on laravel 5.2 - I thought I sent you the laravel.log file but let me check my outbox

Robert M. Springston
CEO and Co-Founder
Quipley, Inc.
333 City Boulevard West
17th Floor
Orange, CA  92868

Phone: 714.937.2010
Mobile: 310.359.3816 | Email: bspringston@quipley.com
http://www.quipley.com

This item/document/material contains CONFIDENTIAL TRADE SECRET INFORMATION owned by Quipley, Inc. and/or its affiliated companies. This information is protected by applicable state law and may be protected by the federal Economic Espionage Act OF 1996 (18 U.S.C. Sec. 1831), which provides for criminal penalties of up to 15 years in prison and/or a $5 million fine for stealing, receiving, possessing and/or duplicating any information contained herein.

**Comment by bspringston** [comment]
Thanks,

Robert M. Springston
CEO and Co-Founder
Quipley, Inc.
333 City Boulevard West
17th Floor
Orange, CA  92868

Phone: 714.937.2010
Mobile: 310.359.3816 | Email: bspringston@quipley.com
http://www.quipley.com

This item/document/material contains CONFIDENTIAL TRADE SECRET INFORMATION owned by Quipley, Inc. and/or its affiliated companies. This information is protected by applicable state law and may be protected by the federal Economic Espionage Act OF 1996 (18 U.S.C. Sec. 1831), which provides for criminal penalties of up to 15 years in prison and/or a $5 million fine for stealing, receiving, possessing and/or duplicating any information contained herein.

**Comment by HarryBosh** [comment]
Laravel 5.1 and 5.2 @AndyWendt  3 months has gone past

**Comment by AndyWendt** [comment]
@HarryBosh I can definitely understand your frustration with free and open source software and the limited time that the devs behind the projects have to contribute.  :smile:   I don't get paid to do this.  

Let's suffice it to say that my life has been crazy nuts recently.

There is also the opportunity for everyone in the open source community to contribute via pull requests.  I have done so on several occasions to other repositories.  I am going to do my best to get to this soon :smile:

**Comment by AndyWendt** [comment]
@bspringston @HarryBosh It now works on 5.1 as of my last test.  Upgrade to version 1.1.1  and you should be good to go.

**Comment by bspringston** [comment]
Thanks Andy.  I'll check it out on 5.2 and let you know how it goes.

**Comment by AndyWendt** [comment]
@bspringston 

The 5.2 issue is because, I just found out, you need to wrap your routes now in a `Route::group`

```php
Route::group(['middleware' => ['web']], function () {
    \Route::get('auths', function() {
        return \Socialite::driver('meetup')->redirect();
    });

    \Route::get('/callback', function () {
        $user = \Socialite::driver('meetup')->user();

        dd($user);
    });
});
```

**Comment by bspringston** [comment]
Works for me on 5.2.  Thanks again Andy!

**Comment by AndyWendt** [comment]
@bspringston You're welcome :)
